name: PR Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get the list of changed files
        id: changes
        run: |
          echo "::set-output name=files::$(jq -r '.pull_request.changed_files[]' < ${GITHUB_EVENT_PATH})"

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Send review request to OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(jq -r '.pull_request.changed_files[].filename' "$GITHUB_EVENT_PATH")

          # Prepare the prompt for ChatGPT (you may modify the instructions as needed)
          PROMPT="다음 코드 변경 사항을 검토하고 피드백을 제공해주세요:\n\n"

          # Append each changed file's contents to the prompt
          for FILE in $CHANGED_FILES; do
            if [ -f "$FILE" ]; then
              PROMPT+="File: $FILE\n"
              PROMPT+="$(cat "$FILE")\n\n"
            fi
          done

          # Call the OpenAI API
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "text-davinci-003",
              "prompt": "'"$PROMPT"'",
              "temperature": 0.5,
              "max_tokens": 500
            }')

          # Extract the review text from the response
          REVIEW=$(echo "$RESPONSE" | jq -r '.choices[0].text')

          # Post the review comment on the PR
          COMMENT_BODY="{\"body\": \"$REVIEW\"}"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$COMMENT_BODY" \
            "${{ github.event.pull_request.comments_url }}"
