name: PR Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get the list of changed files
        id: changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # GitHub API를 통해 변경된 파일 목록을 JSON 형태로 가져옴
          CHANGED_FILES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.url }}/files" | jq -r '.[].filename')
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Send review request to OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # 변경된 파일들을 OpenAI에 보낼 프롬프트로 준비합니다
          PROMPT="코드리뷰해주세요:\n\n"

          for FILE in ${{ steps.changes.outputs.files }}; do
            if [ -f "$FILE" ]; then
              PROMPT+="File: $FILE\n"
              PROMPT+="$(cat "$FILE")\n\n"
            fi
          done

          # OpenAI API에 요청 보내기
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "text-davinci-003",
              "prompt": "'"$PROMPT"'",
              "temperature": 0.5,
              "max_tokens": 500
            }')

          # OpenAI의 응답에서 리뷰 텍스트 추출
          REVIEW=$(echo "$RESPONSE" | jq -r '.choices[0].text')

          # PR에 리뷰 코멘트로 게시
          COMMENT_BODY="{\"body\": \"$REVIEW\"}"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$COMMENT_BODY" \
            "${{ github.event.pull_request.comments_url }}"
